OrganWeb/OrganWeb/Areas/Sistema/Models/Safras/Semente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using OrganWeb.Models;
using OrganWeb.Areas.Sistema.Models.Armazenamento;
using OrganWeb.Areas.Sistema.Models.zBanco;

namespace OrganWeb.Areas.Sistema.Models.Safras
{
    [Table("tbSemente")]
    public class Semente : OrganRepository<Semente>
    {
        [Key]
        [ForeignKey("Estoque")]
        public int IdEstoque { get; set; }

        [Required(ErrorMessage = "O nome é obrigatório.", AllowEmptyStrings = false)]
        [StringLength(30, MinimumLength = 1)]
        public string Nome { get; set; }
        
        [Display(Name = "Descrição")]
        [StringLength(100, MinimumLength = 3)]
        public string Desc { get; set; }

        public virtual Estoque Estoque { get; set; }

        //http://www.macoratti.net/18/03/mvc5_cadprod1.htm
    }
}

OrganWeb/OrganWeb/Areas/Ecommerce/Controllers/AnuncioController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using OrganWeb.Areas.Ecommerce.Models.Vendas;
using OrganWeb.Areas.Ecommerce.Models.API;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OrganWeb.Areas.Ecommerce.Controllers
{
    public class AnuncioController : Controller
    {
        private Produto produto = new Produto();
        private Anuncio anuncio = new Anuncio();
        private ListarUnidades unmd = new ListarUnidades();
        private UnidadeCadastro uncd = new UnidadeCadastro();
        private ApplicationUserManager _userManager;

        public AnuncioController()
        {
        }

        public AnuncioController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> MeusAnuncios(int? page)
        {
            int pagina = page ?? 1;
            var anuncios = await anuncio.GetAll();
            return View(anuncio.GetMeusAnuncios(pagina, anuncios));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> NovoDeEstoque(string Nome, double Qtd)
        {
            unmd = await unmd.GetListarUnidades();
            return View("Novo", new Anuncio { Anunciante = new Anunciante { Usuario = await UserManager.FindByIdAsync(User.Identity.GetUserId()) }, Produto = new Produto { Nome = Nome, Unidades = unmd.UnidadeCadastros }, Quantidade = Qtd });
        }

        public async Task<ActionResult> Novo()
        {
            unmd = await unmd.GetListarUnidades();
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            anuncio = new Anuncio { Anunciante = new Anunciante { Usuario = user }, Produto = new Produto { Unidades = unmd.UnidadeCadastros } };
            return View(anuncio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Novo([Bind(Exclude = "Foto")]Anuncio anuncio)
        {
            unmd = await unmd.GetListarUnidades();
            if (ModelState.IsValid)
            {
                byte[] imageData = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["Foto"];
                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        imageData = binary.ReadBytes(poImgFile.ContentLength);
                    }
                    anuncio.Foto = imageData;
                }
                anuncio.Data = DateTime.Today;
                if (await unmd.GetByID(anuncio.Produto.UM) == null)
                {
                    anuncio.Produto.Unidades = unmd.UnidadeCadastros;
                    uncd = new UnidadeCadastro()
                    {
                        Id = anuncio.Produto.UM,
                        Desc = anuncio.Produto.Unidades.Where(x => x.Id == anuncio.Produto.UM).Select(x => x.Desc).FirstOrDefault().ToString()
                    };
                    uncd.Add(uncd);
                    await uncd.Save();
                }
                anuncio.Produto.Add(anuncio.Produto);
                await anuncio.Produto.Save();

                anuncio.Status = true;
                anuncio.IdProduto = anuncio.Produto.Id;
                anuncio.IdAnunciante = User.Identity.GetUserId();
                anuncio.Add(anuncio);
                await anuncio.Save();

                return RedirectToAction("Detalhes", new { id = anuncio.Id });
            }
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            anuncio.Anunciante = new Anunciante { Usuario = user };
            anuncio.Produto.Unidades = unmd.UnidadeCadastros;
            return View(anuncio);
        }

        public async Task<ActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetAnuncio(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            anuncio.Comentarios = await new Comentario().GetComentarios(anuncio);
            anuncio.Avaliacoes = await new Avaliacao().GetAvaliacoes(anuncio);
            return View(anuncio);
        }

        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetByID(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            unmd = await unmd.GetListarUnidades();
            anuncio.Produto.Unidades = unmd.UnidadeCadastros;
            return View(anuncio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar([Bind(Exclude = "Foto")]Anuncio anuncio)
        {
            if (ModelState.IsValid)
            {
                if (anuncio.Foto != null)
                {
                    byte[] imageData = null;
                    if (Request.Files.Count > 0)
                    {
                        HttpPostedFileBase poImgFile = Request.Files["Foto"];
                        using (var binary = new BinaryReader(poImgFile.InputStream))
                        {
                            imageData = binary.ReadBytes(poImgFile.ContentLength);
                        }
                    }
                    anuncio.Foto = imageData;
                }
                anuncio.Update(anuncio);
                await anuncio.Save();
                if (await unmd.GetByID(anuncio.Produto.UM) == null)
                {
                    anuncio.Produto.Unidades = unmd.UnidadeCadastros;
                    var uncd = new UnidadeCadastro()
                    {
                        Id = anuncio.Produto.UM,
                        Desc = anuncio.Produto.Unidades.Where(x => x.Id == anuncio.Produto.UM).Select(x => x.Desc).FirstOrDefault().ToString()
                    };
                    unmd.Add(uncd);
                    await unmd.Save();
                }
                anuncio.Produto.Update(anuncio.Produto);
                await anuncio.Produto.Save();
                //TODO: testar alteração de anúncio
                ViewBag.SuccessMessage = "Seu anúncio " + anuncio.Nome + " foi alterado com sucesso.";
                ViewBag.Id = anuncio.Id;
                ModelState.Clear();
                return View();
            }
            anuncio.Produto.Unidades = unmd.UnidadeCadastros;
            return View(anuncio);
        }

        public async Task<ActionResult> Excluir(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetByID(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            return View(anuncio);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ExcluirConfirmado(Anuncio anuncio)
        {
            anuncio.Status = false;
            anuncio.Update(anuncio);
            await anuncio.Save();
            ViewBag.SuccessMessage = "Seu anúncio " + anuncio.Nome + " foi desativado.";
            ModelState.Clear();
            return View();
        }

        public FileContentResult FotoDoAnuncio(Anuncio anuncio)
        {
            if (anuncio.Foto == null)
            {
                string fileName = HttpContext.Server.MapPath(@"~/Imagens/admin.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");
            }
            return new FileContentResult(anuncio.Foto, "image/jpeg");
        }
    }
}

OrganWeb/OrganWeb/Areas/Sistema/Controllers/SementeController.cs
using OrganWeb.Areas.Sistema.Models.API;
using OrganWeb.Areas.Sistema.Models.Armazenamento;
using OrganWeb.Areas.Sistema.Models.Safras;
using OrganWeb.Areas.Sistema.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OrganWeb.Areas.Sistema.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SementeController : Controller
    {
        private Semente semente = new Semente();
        private Estoque estoque = new Estoque();
        private ListarUnidades unmd = new ListarUnidades();
        private UnidadeCadastro uncd = new UnidadeCadastro();

        public ActionResult Sementes()
        {
            return RedirectToAction("Index", "Estoque");
        }

        public async Task<ActionResult> Create()
        {
            var responseModel = await unmd.GetListarUnidades();
            semente = new Semente()
            {
                Estoque = new Estoque
                {
                    Unidades = responseModel.UnidadeCadastros,
                    Fornecedores = await new Fornecedor().GetAll()
                }
            };
            return View(semente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Semente semente)
        {
            if (ModelState.IsValid)
            {
                var estoque = new Estoque()
                {
                    Qtd = semente.Estoque.Qtd,
                    UM = semente.Estoque.UM,
                    IdFornecedor = semente.Estoque.IdFornecedor
                };
                estoque.Add(estoque);
                await estoque.Save();
                estoque.Dispose();

                semente.IdEstoque = estoque.Id;
                semente.Estoque = null;
                estoque = null;
                semente.Add(semente);
                await semente.Save();
                semente.Dispose();

                return RedirectToAction("Index", "Estoque");
            }
            return View(semente);
        }

        public async Task<ActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            semente = await semente.GetByID(id);
            if (semente == null)
            {
                return HttpNotFound();
            }
            return View(semente);
        }

        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            semente = await semente.GetByID(id);
            if (semente == null)
            {
                return HttpNotFound();
            }
            semente.Estoque.Fornecedores = await new Fornecedor().GetAll();
            return View(semente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar(Semente semente)
        {
            if (ModelState.IsValid)
            {
                semente.Update(semente);
                await semente.Save();
                estoque.Update(semente.Estoque);
                await estoque.Save();
                return RedirectToAction("Index", "Estoque");
            }
            semente.Estoque.Fornecedores = await new Fornecedor().GetAll();
            return View(semente);
        }

        public async Task<ActionResult> Excluir(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            semente = await semente.GetByID(id);
            if (semente == null)
            {
                return HttpNotFound();
            }
            return View(semente);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ExcluirConfirmado(Semente semente)
        {
            semente.Delete(semente.IdEstoque);
            await semente.Save();

            return RedirectToAction("Index", "Estoque");
        }
    }
}

OrganWeb/OrganWeb/Areas/Sistema/Views/Semente/Create.cshtml
@model OrganWeb.Areas.Sistema.Models.Safras.Semente

@using (Html.BeginForm("Create", "Semente", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Nova Semente</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Estoque.Qtd, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Estoque.Qtd, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Estoque.Qtd, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Estoque.UM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Estoque.UM, new SelectList(Model.Estoque.Unidades, "Id", "Desc"))
            @Html.ValidationMessageFor(model => model.Estoque.UM, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Estoque.IdFornecedor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Estoque.IdFornecedor, new SelectList(Model.Estoque.Fornecedores, "Id", "Nome"))
            @Html.ValidationMessageFor(model => model.Estoque.IdFornecedor, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="modal-footer">
        <div class="col-md-offset-2 col-md-4">
            <input type="submit" value="Adicionar" class="btn pull-right" />
        </div>
    </div>

</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OrganWeb/OrganWeb/Areas/Sistema/Views/Semente/Detalhes.cshtml
@model OrganWeb.Areas.Sistema.Models.Safras.Semente

<div>
    <h4>Detalhes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        @if (Model.Desc != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Desc)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Desc)
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.Estoque.Qtd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estoque.Qtd) @Html.DisplayFor(model => model.Estoque.UM)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Estoque.Fornecedor.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estoque.Fornecedor.Nome)
        </dd>
    </dl>
</div>

@using (Html.BeginForm("NovoDeEstoque", "Anuncio", new { area = "Ecommerce", Nome = Model.Nome, Qtd = Model.Estoque.Qtd }, FormMethod.Post, new { @class = "" }))
{
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-addmodal" data-save="ajax-modal">Criar venda no ecommerce</button>
}

OrganWeb/OrganWeb/Areas/Sistema/Views/Semente/Editar.cshtml
@model OrganWeb.Areas.Sistema.Models.Safras.Semente

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdEstoque)
        @Html.HiddenFor(model => model.Estoque.UM)
        @Html.HiddenFor(model => model.Estoque.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Estoque.Qtd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estoque.Qtd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estoque.Qtd, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Estoque.UM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Estoque.UM)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Estoque.IdFornecedor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Estoque.IdFornecedor, new SelectList(Model.Estoque.Fornecedores, "Id", "Nome"))
                @Html.ValidationMessageFor(model => model.Estoque.IdFornecedor, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Estoque")
</div>

OrganWeb/OrganWeb/Areas/Sistema/Views/Semente/Excluir.cshtml
@model OrganWeb.Areas.Sistema.Models.Safras.Semente

<h3>Tem certeza que deseja deletar esse registro?</h3>
<div>
    <h4>Semente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Solo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Solo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncSol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncSol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncVento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncVento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Acidez)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Acidez)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>