OrganWeb/OrganWeb/Areas/Ecommerce/Controllers/AnuncioController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using OrganWeb.Areas.Ecommerce.Models.Vendas;
using OrganWeb.Areas.Ecommerce.Models.API;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OrganWeb.Areas.Ecommerce.Controllers
{
    public class AnuncioController : Controller
    {
        private Produto produto = new Produto();
        private Anuncio anuncio = new Anuncio();
        private ListarUnidades unmd = new ListarUnidades();
        private UnidadeCadastro uncd = new UnidadeCadastro();
        private ApplicationUserManager _userManager;

        public AnuncioController()
        {
        }

        public AnuncioController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> MeusAnuncios(int? page)
        {
            int pagina = page ?? 1;
            var anuncios = await anuncio.GetAll();
            return View(anuncio.GetMeusAnuncios(pagina, anuncios));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> NovoDeEstoque(string Nome, double Qtd)
        {
            unmd = await unmd.GetListarUnidades();
            return View("Novo", new Anuncio { Anunciante = new Anunciante { Usuario = await UserManager.FindByIdAsync(User.Identity.GetUserId()) }, Produto = new Produto { Nome = Nome, Unidades = unmd.UnidadeCadastros }, Quantidade = Qtd });
        }

        public async Task<ActionResult> Novo()
        {
            unmd = await unmd.GetListarUnidades();
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            anuncio = new Anuncio { Anunciante = new Anunciante { Usuario = user }, Produto = new Produto { Unidades = unmd.UnidadeCadastros } };
            return View(anuncio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Novo([Bind(Exclude = "Foto")]Anuncio anuncio)
        {
            unmd = await unmd.GetListarUnidades();
            if (ModelState.IsValid)
            {
                byte[] imageData = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["Foto"];
                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        imageData = binary.ReadBytes(poImgFile.ContentLength);
                    }
                    anuncio.Foto = imageData;
                }
                anuncio.Data = DateTime.Today;
                if (await unmd.GetByID(anuncio.Produto.UM) == null)
                {
                    anuncio.Produto.Unidades = unmd.UnidadeCadastros;
                    uncd = new UnidadeCadastro()
                    {
                        Id = anuncio.Produto.UM,
                        Desc = anuncio.Produto.Unidades.Where(x => x.Id == anuncio.Produto.UM).Select(x => x.Desc).FirstOrDefault().ToString()
                    };
                    uncd.Add(uncd);
                    await uncd.Save();
                }
                anuncio.Produto.Add(anuncio.Produto);
                await anuncio.Produto.Save();

                anuncio.Status = true;
                anuncio.IdProduto = anuncio.Produto.Id;
                anuncio.IdAnunciante = User.Identity.GetUserId();
                anuncio.Add(anuncio);
                await anuncio.Save();

                return RedirectToAction("Detalhes", new { id = anuncio.Id });
            }
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            anuncio.Anunciante = new Anunciante { Usuario = user };
            anuncio.Produto.Unidades = unmd.UnidadeCadastros;
            return View(anuncio);
        }

        public async Task<ActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetAnuncio(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            anuncio.Comentarios = await new Comentario().GetComentarios(anuncio);
            anuncio.Avaliacoes = await new Avaliacao().GetAvaliacoes(anuncio);
            return View(anuncio);
        }

        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetByID(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            unmd = await unmd.GetListarUnidades();
            anuncio.Produto.Unidades = unmd.UnidadeCadastros;
            return View(anuncio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar([Bind(Exclude = "Foto")]Anuncio anuncio)
        {
            if (ModelState.IsValid)
            {
                if (anuncio.Foto != null)
                {
                    byte[] imageData = null;
                    if (Request.Files.Count > 0)
                    {
                        HttpPostedFileBase poImgFile = Request.Files["Foto"];
                        using (var binary = new BinaryReader(poImgFile.InputStream))
                        {
                            imageData = binary.ReadBytes(poImgFile.ContentLength);
                        }
                    }
                    anuncio.Foto = imageData;
                }
                anuncio.Update(anuncio);
                await anuncio.Save();
                if (await unmd.GetByID(anuncio.Produto.UM) == null)
                {
                    anuncio.Produto.Unidades = unmd.UnidadeCadastros;
                    var uncd = new UnidadeCadastro()
                    {
                        Id = anuncio.Produto.UM,
                        Desc = anuncio.Produto.Unidades.Where(x => x.Id == anuncio.Produto.UM).Select(x => x.Desc).FirstOrDefault().ToString()
                    };
                    unmd.Add(uncd);
                    await unmd.Save();
                }
                anuncio.Produto.Update(anuncio.Produto);
                await anuncio.Produto.Save();
                //TODO: testar alteração de anúncio
                ViewBag.SuccessMessage = "Seu anúncio " + anuncio.Nome + " foi alterado com sucesso.";
                ViewBag.Id = anuncio.Id;
                ModelState.Clear();
                return View();
            }
            anuncio.Produto.Unidades = unmd.UnidadeCadastros;
            return View(anuncio);
        }

        public async Task<ActionResult> Excluir(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetByID(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            return View(anuncio);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ExcluirConfirmado(Anuncio anuncio)
        {
            anuncio.Status = false;
            anuncio.Update(anuncio);
            await anuncio.Save();
            ViewBag.SuccessMessage = "Seu anúncio " + anuncio.Nome + " foi desativado.";
            ModelState.Clear();
            return View();
        }

        public FileContentResult FotoDoAnuncio(Anuncio anuncio)
        {
            if (anuncio.Foto == null)
            {
                string fileName = HttpContext.Server.MapPath(@"~/Imagens/admin.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");
            }
            return new FileContentResult(anuncio.Foto, "image/jpeg");
        }
    }
}

OrganWeb/OrganWeb/Areas/Ecommerce/Controllers/LojaController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using OrganWeb.Areas.Ecommerce.Models;
using OrganWeb.Areas.Ecommerce.Models.Vendas;
using OrganWeb.Areas.Ecommerce.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OrganWeb.Areas.Ecommerce.Controllers
{
    public class LojaController : Controller
    {
        private Anuncio anuncio = new Anuncio();
        private ApplicationUserManager _userManager;

        public LojaController()
        {
        }

        public LojaController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public async Task<ActionResult> Pesquisa(int? page, string s)
        {
            int pagina = page ?? 1;
            var anuncios = await anuncio.GetAnuncios();
            return View(anuncio.GetAnunciosFiltro(pagina, s, anuncios));
        }

        public async Task<ActionResult> Index(int? pagedesc, int? pagenovos)
        {
            int pagecdesc = pagedesc ?? 1;
            int pagenovo = pagenovos ?? 1;
            var anuncios = await anuncio.GetAnuncios();
            var view = new ViewLoja
            {
                AnunciosComDesconto = anuncio.GetAnunciosEmPromocao(pagecdesc, anuncios),
                AnunciosRecentes = anuncio.GetAnunciosRecentes(pagenovo, anuncios)
            };
            return View(view);
        }

        public async Task<FileContentResult> FotoDoAnuncio(int? anuncio)
        {
            Anuncio anuncioo = new Anuncio();
            if(anuncio != null)
                anuncioo = await anuncioo.GetByID(anuncio);
            if (anuncio == null ||anuncioo.Foto == null)
            {
                string fileName = HttpContext.Server.MapPath(@"~/Imagens/admin.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");
            }
            return new FileContentResult(anuncioo.Foto, "image/png");
        }

        public async Task<ActionResult> Categoria(int? page, int cat)
        {
            int pagina = page ?? 1;
            var anuncios = await anuncio.GetAnuncios();
            ViewBag.Categoria = cat;
            return View(anuncio.GetAnunciosCategoria(pagina, cat, anuncios));
        }
    }
}

OrganWeb/OrganWeb/Areas/Ecommerce/Controllers/PedidoController.cs
using Microsoft.AspNet.Identity;
using OrganWeb.Areas.Ecommerce.Models.Vendas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using OrganWeb.Areas.Ecommerce.Models.API;
using OrganWeb.Areas.Ecommerce.Models.Endereco;
using OrganWeb.Areas.Ecommerce.Models.Financeiro;
using OrganWeb.Areas.Ecommerce.Models.ViewsBanco;

namespace OrganWeb.Areas.Ecommerce.Controllers
{
    public class PedidoController : Controller
    {
        private Carrinho carrinho = new Carrinho();
        private Anuncio anuncio = new Anuncio();
        private Estado estado = new Estado();
        private PedidoAnuncio pedidoAnuncio = new PedidoAnuncio();

        [Authorize]
        public async Task<ActionResult> Index()
        {
            return View(await new VwPedido().GetPedidosCliente());
        }

        [Authorize]
        public async Task<ActionResult> Checkout()
        {
            //Verifica se ele não tem itens no carrinho
            var itenscarrinho = await carrinho.GetCarrinho();
            if (itenscarrinho?.Count() <= 0)
            {
                //Se não tiver ele volta pro carrinho com uma mensagem de erro que não tem itens lá
                return RedirectToAction("Index", "Carrinho");
            }
            //Envia o carrinho pro checkout
            var (QtdItens, Subtotal) = await carrinho.GetQtdETotalCarrinho();
            return View(new Pedido
            {
                Endereco = new Endereco { Logradouro = new Logradouro { Bairro = new Bairro { Cidade = new Cidade { Estados = await estado.GetAll() } } } },
                Carrinhos = itenscarrinho,
                IdUsuario = User.Identity.GetUserId(),
                Subtotal = Subtotal
            });
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Checkout(Pedido pedido)
        {
            pedido.Carrinhos = await carrinho.GetCarrinho();
            pedido.IdUsuario = User.Identity.GetUserId();
            pedido.Status = 1;
            pedido.Data = DateTime.Today;
            pedido.Endereco.CEP = pedido.CEPEntrega;
            pedido.Endereco.Logradouro.CEP = pedido.CEPEntrega;

            ModelState.Remove("Endereco.CEP");
            ModelState.Remove("Endereco.Logradouro.CEP");

            if (ModelState.IsValid)
            {   
                var cep = await new Endereco().GetByID(pedido.CEPEntrega);
                if (cep == null)
                {
                    cep = new Endereco()
                    {
                        CEP = pedido.CEPEntrega
                    };
                    cep.Add(cep);
                    await cep.Save();
                }

                var cidade = new Cidade()
                {
                    Nome = pedido.Endereco.Logradouro.Bairro.Cidade.Nome,
                    IdEstado = pedido.Endereco.Logradouro.Bairro.Cidade.IdEstado
                };
                cidade.Add(cidade);
                await cidade.Save();

                var bairro = new Bairro()
                {
                    Nome = pedido.Endereco.Logradouro.Bairro.Nome,
                    IdCidade = cidade.Id
                };
                bairro.Add(bairro);
                await bairro.Save();

                var rua = new Logradouro()
                {
                    CEP = cep.CEP,
                    Nome = pedido.Endereco.Logradouro.Nome,
                    IdBairro = bairro.Id
                };
                rua.Add(rua);
                await rua.Save();

                var pagamento = pedido.Pagamento;
                pagamento.Add(pagamento);
                await pagamento.Save();

                pedido.IdPagamento = pagamento.Id;

                var grupoanunciantes = pedido.Carrinhos.GroupBy(p => p.Anuncio.Anunciante, p => p, (key, c) => new { Anunciante = key, pedido.Carrinhos });

                foreach (var anunciante in grupoanunciantes)
                {
                    foreach (var carrito in anunciante.Carrinhos.Where(x => x.Anuncio.Anunciante == anunciante.Anunciante))
                    {
                        var valorfrete = await MetodosAPI.GetValorDoFrete(carrito.Anuncio.Anunciante.CEP, pedido.CEPEntrega);
                        pedido.ValFrete = valorfrete.ValorFrete;
                        pedido.Endereco = null;
                        pedido.Add(pedido);
                        await pedido.Save();
                        pedidoAnuncio = new PedidoAnuncio
                        {
                            IdAnuncio = carrito.IdAnuncio,
                            IdPedido = pedido.Id,
                            Qtd = carrito.Qtd
                        };
                        pedidoAnuncio.Add(pedidoAnuncio);
                        await pedidoAnuncio.Save();
                    }
                }
                ViewBag.SuccessMessage = "Seu pedido foi efetuado com sucesso! Aguarde a confirmação do anunciante.";
                ModelState.Clear();
                return View();
            }
            var (QtdItens, Subtotal) = await carrinho.GetQtdETotalCarrinho();
            pedido.Endereco.Logradouro.Bairro.Cidade.Estados = await estado.GetAll();
            pedido.Subtotal = Subtotal;
            return View(pedido);
        }

        [HttpPost]
        public async Task<ActionResult> PostFrete(string cep)
        {
            var carrinhos = await carrinho.GetCarrinho();
            string valor = await MetodosAPI.GetFreteFromCarrinhoAsync(carrinhos, cep);
            return Json(new { result = true, frete = valor });
        }
    }
}

OrganWeb/OrganWeb/Views/Shared/_LayoutEcommerce.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="~/Content/jquery-ui.css">

    @Scripts.Render("~/bundles/fontawesome")
    <link href="~/Content/materialdesignicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/aos.css">
    <link href="~/Content/ecommercestyle.css" rel="stylesheet">
</head>
<body>

    <!-- HEADER -->
    <header id="header" class="header-area style-01 layout-03">
        <div class="header-bottom hidden-sm hidden-xs">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 col-md-3">
                        <a href="/Ecommerce" class="biolife-logo"><img src="~/Imagens/logo.png" alt="biolife logo" width="135" height="34"></a>
                    </div>
                    <div class="col-lg-10 col-md-9 padding-top-2px">
                        <div class="header-search-bar layout-01">
                            @using (Html.BeginForm("Pesquisa", "Loja", FormMethod.Get))
                            {
                                @Html.TextBox("s", null, new { @class = "input-text", @placeholder = "Procurar" })
                                <button type="submit" class="btn-submit"><i class="biolife-icon mdi mdi-find-replace"></i></button>
                            }
                        </div>
                        <div class="biolife-cart-info">
                            <div class="wishlist-block hidden-sm hidden-xs">
                                <a href="/Ecommerce/Wishlist/Index" class="link-to">
                                    <span class="icon-qty-combine">
                                        <i class="mdi mdi-heart-outline biolife-icon"></i>
                                    </span>
                                </a>
                            </div>
                            <div class="minicart-block">
                                <div class="minicart-contain">
                                    <a href="/Ecommerce/Carrinho/Index" class="link-to">
                                        <span class="icon-qty-combine">
                                            <i class="mdi mdi-cart-outline biolife-icon"></i>
                                            <span class="qty">@{Html.RenderAction("SumarioCarrinho", "Carrinho");}
                                    </a>
                                </div>
                            </div>
                            <div class="login-item minicart-contain hidden-sm hidden-xs">
                                <nav class="navbar navbar-expand-lg main-navbar">
                                    @Html.Partial("_LoginEcoPartial")
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Begin Header Bottom Area -->
        <div class="menu-bottom header-sticky d-none d-lg-block d-xl-block">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="hb-menu">
                            <nav>
                                <ul>
                                    <li>@Html.ActionLink("Início", "Index", "Loja")</li>
                                    <li><a href="#">Categoria</a></li>
                                    <li>@Html.ActionLink("Vender", "Novo", "Anuncio")</li>
                                    <li><a href="#">Contato</a></li>
                                    <li><a href="/Sistema/">Organ</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Header Bottom Menu Area End Here -->

    </header>

    <div>
        @RenderBody()
    </div>

    <!-- FOOTER -->
    <!-- FOOTER -->
    <footer id="footer">
        <!-- /top footer -->
        <!-- bottom footer -->
        <div id="bottom-footer" class="section">
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-12 text-center">
                        <span class="copyright">
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> Todos os direitos reservados
                        </span>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /bottom footer -->
    </footer>
    <!-- /FOOTER -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/Scripts/main.js")" type="text/javascript"></script>
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

OrganWeb/OrganWeb/Views/Shared/_LoginEcoPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="@Url.Action("FotoDoUsuario", "Account", new { Area = "Ecommerce", id = User.Identity.GetUserId() })" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">Olá, @Html.DisplayName(User.Identity.GetUserName())</div>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
            <a href="#" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Perfil
            </a>

            <a href="@Url.Action("Index", "Pedido", new { Area = "Ecommerce" })" class="dropdown-item has-icon">
                <i class="fas fa-check"></i> Meus pedidos
            </a>

            <a href="@Url.Action("Configurações", "Index", "Manage", "routeValues: null")" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Configurações
            </a>

            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                @Html.ActionLink("Configurações", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Configurações", @class = "dropdown-item" })
                <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()"> Fazer logoff</a>
            </div>

            <div class="dropdown-divider"></div>

            <a href="javascript:document.getElementById('logoutForm').submit()" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Sair
            </a>
        </div>
    }
}
else
{
    <a href="@Url.Action("Login", "Account", new { Area = "Ecommerce", returnUrl = this.Request.RawUrl })" class="login-link"><i class="biolife-icon mdi mdi-account-outline"></i>Login</a>
    <a href="@Url.Action("Registro", "Account", new { Area = "Ecommerce" })" class="login-link"><i class="biolife-icon mdi mdi-account-outline"></i>Registro</a>
}

OrganWeb/OrganWeb/Views/Shared/_Menu.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <ul class="navbar-nav navbar-nav-right">
        <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                <img src="~/Imagens/admin.jpg" alt="profile" />
                <span class="nav-profile-name">@Html.DisplayName(User.Identity.GetUserName())</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                @Html.ActionLink("Configurações", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Configurações", @class = "dropdown-item" })
                <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()"> Fazer logoff</a>
            </div>
        </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
        <i class="fa fa-bars"></i>
    </button>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Registre-se", "RegistroEco", "Account", new { Area = "Ecommerce" }, new { })</li>
        <li>@Html.ActionLink("Login", "Login", "Account", new { Area = "Ecommerce" }, new { })</li>
    </ul>
}