OrganWeb/OrganWeb/Areas/Sistema/Controllers/ControleController.cs
using OrganWeb.Areas.Sistema.Models.Controles;
using OrganWeb.Areas.Sistema.Models.Funcionarios;
using OrganWeb.Areas.Sistema.Models.Praga_e_Doenca;
using OrganWeb.Areas.Sistema.Models.ViewModels;
using OrganWeb.Areas.Sistema.Models.ViewsBanco.Estoque;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace OrganWeb.Areas.Sistema.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ControleController : Controller
    {
        private Controle controle = new Controle();
        private VwControle vwcontrole = new VwControle();
        private ItensControle itenscontrole = new ItensControle();
        private FuncControle funccontrole = new FuncControle();
        private ControlePD controlepd = new ControlePD();
        private VwItems vwItems = new VwItems();
        private PragaOrDoenca pd = new PragaOrDoenca();
        private Funcionario func = new Funcionario();
        private List<int> ItensEstoque = new List<int>();
        private List<double> Quantidades = new List<double>();
        private Dictionary<int, double> ItensQuantidade = new Dictionary<int, double>();

        public ActionResult Index()
        {
            return RedirectToAction("Index", "PragaDoenca");
        }

        public async Task<ActionResult> Create()
        {
            var itens = await vwItems.GetAll();
            var model = new CreateControleViewModel
            {
                VwItems = itens.Where(x => x.Tipo != "Semente" && x.Tipo != "Produto").ToList(),
                Funcionarios = await func.GetAll(),
                PragaOrDoencas = await pd.GetAll()
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateControleViewModel model, int[] IdPD, int[] IdFunc, int[] IdEstoque, int[] QtdUsada)
        {
            if (ModelState.IsValid)
            {
                controle = new Controle
                {
                    Desc = model.Desc,
                    Status = model.Status,
                    Efic = model.Efic,
                    NumLiberacoes = model.NumLiberacoes
                };
                controle.Add(controle);
                await controle.Save();

                foreach (var item in model.IdPD)
                {
                    controlepd.Add(new ControlePD { IdControle = controle.Id, IdPD = item });
                    await controlepd.Save();
                }

                foreach (var item in model.IdFunc)
                {
                    funccontrole.Add(new FuncControle { IdControle = controle.Id, IdFunc = item });
                    await funccontrole.Save();
                }

                //Primeiro adiciona os dois valores de array em uma lista
                foreach (var item in model.IdEstoque)
                {
                    ItensEstoque.Add(item);
                }
                foreach (var item in model.QtdUsada)
                {
                    Quantidades.Add(item);
                }

                //https://stackoverflow.com/questions/2434593/create-a-dictionary-using-2-lists-using-linq
                //Então eu crio um dicionário com as duas listas
                ItensQuantidade = ItensEstoque.Zip(Quantidades, (i, q) => new { Key = i, Value = q })
                     .ToDictionary(x => x.Key, x => x.Value);

                //https://stackoverflow.com/questions/141088/what-is-the-best-way-to-iterate-over-a-dictionary
                //Agora eu faço um foreach no dicionário para inserir os dois valores ao mesmo tempo (já que vão juntos na tabela)
                foreach (KeyValuePair<int, double> entry in ItensQuantidade)
                {
                    itenscontrole.Add(new ItensControle { IdControle = controle.Id, IdEstoque = entry.Key, QtdUsada = entry.Value });
                    await itenscontrole.Save();
                }

                return RedirectToAction("Index");
            }
            var itens = await vwItems.GetAll();
            model.VwItems = await itens.AsQueryable().Where(x => x.Tipo != "Semente" && x.Tipo != "Produto").ToListAsync();
            model.Funcionarios = await func.GetAll();
            model.PragaOrDoencas = await pd.GetAll();
            return View(model);
        }
        
        public async Task<ActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vwcontrole = await vwcontrole.GetByID(id);
            if (vwcontrole == null)
            {
                return HttpNotFound();
            }
            return View(vwcontrole);
        }

        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            controle = await controle.GetByID(id);
            if (controle == null)
            {
                return HttpNotFound();
            }
            return View(controle);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar(Controle controle)
        {
            if (ModelState.IsValid) {
                controle.Update(controle);
                await controle.Save();
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Excluir(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            controle = await controle.GetByID(id);
            if (controle == null)
            {
                return HttpNotFound();
            }
            return View(controle);
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Excluir")]
        public async Task<ActionResult> ExcluirConfirmado(Controle controle)
        {
            controle.Delete(controle.Id);
            await controle.Save();
            return RedirectToAction("Index");
        }
    }
}

OrganWeb/OrganWeb/Areas/Sistema/Controllers/PragaDoencaController.cs
using OrganWeb.Areas.Sistema.Models.Administrativo;
using OrganWeb.Areas.Sistema.Models.Praga_e_Doenca;
using OrganWeb.Areas.Sistema.Models.ViewModels;
using OrganWeb.Areas.Sistema.Models.ViewsBanco.Estoque;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OrganWeb.Areas.Sistema.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PragaDoencaController : Controller
    {
        private Area area = new Area();
        private AreaPD areapd = new AreaPD();
        private PragaOrDoenca praga = new PragaOrDoenca();
        private VwPragaOrDoenca vwpraga = new VwPragaOrDoenca();
        private VwControle vwControle = new VwControle();
        
        public async Task<ActionResult> Index(int? pagedoenca, int? pagecont)
        {
            int pdoenca = pagedoenca ?? 1;
            int pcont = pagecont ?? 1;
            return View(new ViewPragaControle { PragaOrDoencas = await vwpraga.GetPagedAll(pdoenca), Controles = await vwControle.GetPagedAll(pcont)});
        }

        public async Task<ActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vwpraga = await vwpraga.GetByID(id);
            if (vwpraga == null)
            {
                return HttpNotFound();
            }
            return View(vwpraga);
        }

        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            praga = await praga.GetByID(id);
            if (praga == null)
            {
                return HttpNotFound();
            }
            return View(praga);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar(PragaOrDoenca pragadoenca)
        {
            if (ModelState.IsValid)
            {
                switch (pragadoenca.PragDoe)
                {
                    case "Praga":
                        pragadoenca.PD = true;
                        break;
                    default:
                        pragadoenca.PD = false;
                        break;
                }
                praga = new PragaOrDoenca
                {
                    Id = pragadoenca.Id,
                    Nome = pragadoenca.Nome,
                    PD = pragadoenca.PD
                };
                praga.Update(praga);
                await praga.Save();
                return RedirectToAction("Index");
            }
            return View(pragadoenca);
        }

        public async Task<ActionResult> Create()
        {
            var view = new PragaOrDoenca
            {
                Areas = await area.GetAll()
            };
            return View(view);
        }

        [HttpPost]
        public async Task<ActionResult> Create(PragaOrDoenca pragadoenca, int[] IdArea)
        {
            if (ModelState.IsValid)
            {
                switch(pragadoenca.PragDoe)
                {
                    case "Praga":
                        pragadoenca.PD = true;
                        break;
                    default:
                        pragadoenca.PD = false;
                        break;
                }
                var pd = new PragaOrDoenca
                {
                    Nome = pragadoenca.Nome,
                    PD = pragadoenca.PD
                };
                pd.Add(pd);
                await pd.Save();
                foreach (var item in IdArea)
                {
                    areapd.Add(new AreaPD { IdArea = item, IdPd = pd.Id, Status = true });
                    await areapd.Save();
                }
                return RedirectToAction("Index");
            }
            pragadoenca.Areas = await area.GetAll();
            return View(pragadoenca);
        }
    }
}

OrganWeb/OrganWeb/Areas/Sistema/Views/PragaDoenca/Create.cshtml
@model OrganWeb.Areas.Sistema.Models.Praga_e_Doenca.PragaOrDoenca

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Adicionar praga ou doença</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control campo" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-6">
                @Html.RadioButtonFor(model => model.PragDoe, "Praga", new { @class = "with-gap" })
                <label for="Praga">Praga</label>
            </div>
            <div class="col-sm-6">
                @Html.RadioButtonFor(model => model.PragDoe, "Doença", new { @class = "with-gap" })
                <label for="Doenca">Doença</label>
            </div>
            @Html.ValidationMessageFor(model => model.PragDoe, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col">
                @Html.LabelFor(model => model.Areas, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col">
                @Html.DropDownList("IdArea", new MultiSelectList(Model.Areas, "Id", "Nome"), new { multiple = "multiple", id = "areas", @class = "campo" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

OrganWeb/OrganWeb/Areas/Sistema/Views/PragaDoenca/Detalhes.cshtml
@model OrganWeb.Areas.Sistema.Models.ViewsBanco.Estoque.VwPragaOrDoenca

<div>
    <h4>Detalhes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Areas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Areas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OrganWeb/OrganWeb/Areas/Sistema/Views/PragaDoenca/Editar.cshtml
@model OrganWeb.Areas.Sistema.Models.Praga_e_Doenca.PragaOrDoenca

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Editar</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <div class="col">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
        </div>
        <div class="col">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control campo" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row">
        <div class="form-group row">
            <div class="col-sm-6">
                @Html.RadioButtonFor(model => model.PragDoe, "Praga", new { @class = "with-gap" })
                <label for="Praga">Praga</label>
            </div>
            <div class="col-sm-6">
                @Html.RadioButtonFor(model => model.PragDoe, "Doença", new { @class = "with-gap" })
                <label for="Doenca">Doença</label>
            </div>
            @Html.ValidationMessageFor(model => model.PragDoe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

OrganWeb/OrganWeb/Areas/Sistema/Views/PragaDoenca/Index.cshtml
@model OrganWeb.Areas.Sistema.Models.ViewModels.ViewPragaControle
@using PagedList.Mvc;
@{
    ViewBag.Title = "Pragas e doenças";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />

<section class="section">
    <div class="tablecontainer">
        <div class="section-header">
            <h1>Controle de pragas e doenças</h1>
        </div>
        <div class="section-body">
            <div class="row">

                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Pragas e doenças</h4>
                            <div class="card-header-form">
                                <a class="popup btn btn-primary btn-add" href="/Sistema/PragaDoenca/Create">Nova praga/doença</a>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-hover table-striped">
                                    <tr>
                                        <th>Nome</th>
                                        <th>Tipo</th>
                                        <th>Áreas</th>
                                        <th>Status</th>
                                        <th></th>
                                    </tr>
                                    @foreach (var item in Model.PragaOrDoencas)
                                    {
                                        <tr>
                                            <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Tipo)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Areas)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Status)</td>
                                            <td>
                                                <a class="popup btn" href="@Url.Action("Detalhes", "PragaDoenca", new { id = item.Id })"><div class="itemback"><i class="item fa fa-info"></i></div></a>
                                                <a class="popup btn" href="@Url.Action("Editar", "PragaDoenca", new { id = item.Id})"><div class="itemback"><i class="item far fa-edit"></i></div></a>
                                                <a class="popup btn" href="@Url.Action("Excluir", "PragaDoenca", new { id = item.Id})"><div class="itemback"><i class="item far fa-trash-alt"></i></div></a>
                                            </td>
                                        </tr>
                                    }
                                </table>

                                <div class="card-footer text-center">
                                    <nav class="d-inline-block">
                                        Página @(Model.PragaOrDoencas.PageCount < Model.PragaOrDoencas.PageNumber ? 0 : Model.PragaOrDoencas.PageNumber) de @Model.PragaOrDoencas.PageCount
                                        @Html.PagedListPager(Model.PragaOrDoencas, pagedoenca => Url.Action("Index",
                                        new { pagedoenca }), new PagedListRenderOptions
                                         {
                                         LiElementClasses = new string[] { "pagination page-item page-link text-center p1" }
                                         })
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Controles</h4>
                            <div class="card-header-form">
                                <a class="popup btn btn-primary btn-add" href="/Sistema/Controle/Create">Novo controle</a>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-hover table-striped">
                                    <tr>
                                        <th>Data</th>
                                        <th>Nome</th>
                                        <th>Status</th>
                                        <th>Eficiência</th>
                                        <th>Liberações</th>
                                        <th></th>
                                    </tr>
                                    @foreach (var item in Model.Controles)
                                    {
                                        <tr>
                                            <td>@Html.DisplayFor(modelItem => item.Data)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Status)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Eficiencia)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Liberacoes)</td>
                                            <td>
                                                <a class="popup btn" href="@Url.Action("Detalhes", "Controle", new { id = item.Id })"><div class="itemback"><i class="item fa fa-info"></i></div></a>
                                                <a class="popup btn" href="@Url.Action("Editar", "Controle", new { id = item.Id})"><div class="itemback"><i class="item far fa-edit"></i></div></a>
                                                <a class="popup btn" href="@Url.Action("Excluir", "Controle", new { id = item.Id})"><div class="itemback"><i class="item far fa-trash-alt"></i></div></a>
                                            </td>
                                        </tr>
                                    }
                                </table>

                                <div class="card-footer text-center">
                                    <nav class="d-inline-block">
                                        Página @(Model.Controles.PageCount < Model.Controles.PageNumber ? 0 : Model.Controles.PageNumber) de @Model.Controles.PageCount
                                        @Html.PagedListPager(Model.Controles, pagecont => Url.Action("Index",
                                        new { pagecont }), new PagedListRenderOptions
                                         {
                                         LiElementClasses = new string[] { "pagination page-item page-link text-center p1" }
                                         })
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v1.0.5/dist/jBox.all.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/modalui.js"></script>
}