OrganWeb/OrganWeb/Areas/Ecommerce/Controllers/AnuncioController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using OrganWeb.Areas.Ecommerce.Models.Vendas;
using OrganWeb.Areas.Ecommerce.Models.API;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OrganWeb.Areas.Ecommerce.Controllers
{
    public class AnuncioController : Controller
    {
        private Produto produto = new Produto();
        private Anuncio anuncio = new Anuncio();
        private ListarUnidades unmd = new ListarUnidades();
        private UnidadeCadastro uncd = new UnidadeCadastro();
        private ApplicationUserManager _userManager;

        public AnuncioController()
        {
        }

        public AnuncioController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> MeusAnuncios(int? page)
        {
            int pagina = page ?? 1;
            var anuncios = await anuncio.GetAll();
            return View(anuncio.GetMeusAnuncios(pagina, anuncios));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> NovoDeEstoque(string Nome, double Qtd)
        {
            unmd = await unmd.GetListarUnidades();
            return View("Novo", new Anuncio { Anunciante = new Anunciante { Usuario = await UserManager.FindByIdAsync(User.Identity.GetUserId()) }, Produto = new Produto { Nome = Nome, Unidades = unmd.UnidadeCadastros }, Quantidade = Qtd });
        }

        public async Task<ActionResult> Novo()
        {
            unmd = await unmd.GetListarUnidades();
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            anuncio = new Anuncio { Anunciante = new Anunciante { Usuario = user }, Produto = new Produto { Unidades = unmd.UnidadeCadastros } };
            return View(anuncio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Novo([Bind(Exclude = "Foto")]Anuncio anuncio)
        {
            unmd = await unmd.GetListarUnidades();
            if (ModelState.IsValid)
            {
                byte[] imageData = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["Foto"];
                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        imageData = binary.ReadBytes(poImgFile.ContentLength);
                    }
                    anuncio.Foto = imageData;
                }
                anuncio.Data = DateTime.Today;
                if (await unmd.GetByID(anuncio.Produto.UM) == null)
                {
                    anuncio.Produto.Unidades = unmd.UnidadeCadastros;
                    uncd = new UnidadeCadastro()
                    {
                        Id = anuncio.Produto.UM,
                        Desc = anuncio.Produto.Unidades.Where(x => x.Id == anuncio.Produto.UM).Select(x => x.Desc).FirstOrDefault().ToString()
                    };
                    uncd.Add(uncd);
                    await uncd.Save();
                }
                anuncio.Produto.Add(anuncio.Produto);
                await anuncio.Produto.Save();

                anuncio.Status = true;
                anuncio.IdProduto = anuncio.Produto.Id;
                anuncio.IdAnunciante = User.Identity.GetUserId();
                anuncio.Add(anuncio);
                await anuncio.Save();

                return RedirectToAction("Detalhes", new { id = anuncio.Id });
            }
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            anuncio.Anunciante = new Anunciante { Usuario = user };
            anuncio.Produto.Unidades = unmd.UnidadeCadastros;
            return View(anuncio);
        }

        public async Task<ActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetAnuncio(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            anuncio.Comentarios = await new Comentario().GetComentarios(anuncio);
            anuncio.Avaliacoes = await new Avaliacao().GetAvaliacoes(anuncio);
            return View(anuncio);
        }

        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetByID(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            unmd = await unmd.GetListarUnidades();
            anuncio.Produto.Unidades = unmd.UnidadeCadastros;
            return View(anuncio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar([Bind(Exclude = "Foto")]Anuncio anuncio)
        {
            if (ModelState.IsValid)
            {
                if (anuncio.Foto != null)
                {
                    byte[] imageData = null;
                    if (Request.Files.Count > 0)
                    {
                        HttpPostedFileBase poImgFile = Request.Files["Foto"];
                        using (var binary = new BinaryReader(poImgFile.InputStream))
                        {
                            imageData = binary.ReadBytes(poImgFile.ContentLength);
                        }
                    }
                    anuncio.Foto = imageData;
                }
                anuncio.Update(anuncio);
                await anuncio.Save();
                if (await unmd.GetByID(anuncio.Produto.UM) == null)
                {
                    anuncio.Produto.Unidades = unmd.UnidadeCadastros;
                    var uncd = new UnidadeCadastro()
                    {
                        Id = anuncio.Produto.UM,
                        Desc = anuncio.Produto.Unidades.Where(x => x.Id == anuncio.Produto.UM).Select(x => x.Desc).FirstOrDefault().ToString()
                    };
                    unmd.Add(uncd);
                    await unmd.Save();
                }
                anuncio.Produto.Update(anuncio.Produto);
                await anuncio.Produto.Save();
                //TODO: testar alteração de anúncio
                ViewBag.SuccessMessage = "Seu anúncio " + anuncio.Nome + " foi alterado com sucesso.";
                ViewBag.Id = anuncio.Id;
                ModelState.Clear();
                return View();
            }
            anuncio.Produto.Unidades = unmd.UnidadeCadastros;
            return View(anuncio);
        }

        public async Task<ActionResult> Excluir(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetByID(id);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            return View(anuncio);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ExcluirConfirmado(Anuncio anuncio)
        {
            anuncio.Status = false;
            anuncio.Update(anuncio);
            await anuncio.Save();
            ViewBag.SuccessMessage = "Seu anúncio " + anuncio.Nome + " foi desativado.";
            ModelState.Clear();
            return View();
        }

        public FileContentResult FotoDoAnuncio(Anuncio anuncio)
        {
            if (anuncio.Foto == null)
            {
                string fileName = HttpContext.Server.MapPath(@"~/Imagens/admin.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");
            }
            return new FileContentResult(anuncio.Foto, "image/jpeg");
        }
    }
}

OrganWeb/OrganWeb/Areas/Ecommerce/Controllers/CarrinhoController.cs
using OrganWeb.Areas.Ecommerce.Models.Vendas;
using OrganWeb.Areas.Ecommerce.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OrganWeb.Areas.Ecommerce.Controllers
{
    public class CarrinhoController : Controller
    {
        private Carrinho carrinho = new Carrinho();
        private Anuncio anuncio = new Anuncio();
        private List<Carrinho> carrinhos = new List<Carrinho>();

        public async Task<ActionResult> Index()
        {
            carrinhos = await carrinho.GetCarrinho();
            var (QtdItens, ValorTotal) = await carrinho.GetQtdETotalCarrinho();
            var carrinhoViewModel = new CarrinhoViewModel
            {
                Carrinhos = carrinhos,
                ItensTotal = QtdItens,
                ValorTotal = ValorTotal,
            };
            return View(carrinhoViewModel);
        }
        
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddAoCarrinho(int? idAnuncio)
        {
            if (idAnuncio == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetByID(idAnuncio);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            var carrito = await carrinho.GetItemCarrinho(anuncio);
            if (carrito != null && carrito.Qtd + 1 > anuncio.Quantidade)
                return RedirectToAction("Index");
            await carrinho.AddAoCarrinho(anuncio);
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<ActionResult> RemoverDoCarrinho(int? idAnuncio)
        {
            if (idAnuncio == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            anuncio = await anuncio.GetByID(idAnuncio);
            if (anuncio == null)
            {
                return HttpNotFound();
            }
            await carrinho.RemoverDoCarrinho(anuncio);
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<ActionResult> ApagarCarrinho()
        {
            await carrinho.LimparCarrinho();
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public async Task<ActionResult> SumarioCarrinho()
        {
            (int QtdItens, double ValorTotal) = await carrinho.GetQtdETotalCarrinho();
            ViewData["Valor"] = ValorTotal;
            ViewData["CartCount"] = QtdItens;
            return PartialView("SumarioCarrinho");
        }
    }
}

OrganWeb/OrganWeb/Areas/Ecommerce/Controllers/LojaController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using OrganWeb.Areas.Ecommerce.Models;
using OrganWeb.Areas.Ecommerce.Models.Vendas;
using OrganWeb.Areas.Ecommerce.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OrganWeb.Areas.Ecommerce.Controllers
{
    public class LojaController : Controller
    {
        private Anuncio anuncio = new Anuncio();
        private ApplicationUserManager _userManager;

        public LojaController()
        {
        }

        public LojaController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public async Task<ActionResult> Pesquisa(int? page, string s)
        {
            int pagina = page ?? 1;
            var anuncios = await anuncio.GetAnuncios();
            return View(anuncio.GetAnunciosFiltro(pagina, s, anuncios));
        }

        public async Task<ActionResult> Index(int? pagedesc, int? pagenovos)
        {
            int pagecdesc = pagedesc ?? 1;
            int pagenovo = pagenovos ?? 1;
            var anuncios = await anuncio.GetAnuncios();
            var view = new ViewLoja
            {
                AnunciosComDesconto = anuncio.GetAnunciosEmPromocao(pagecdesc, anuncios),
                AnunciosRecentes = anuncio.GetAnunciosRecentes(pagenovo, anuncios)
            };
            return View(view);
        }

        public async Task<FileContentResult> FotoDoAnuncio(int? anuncio)
        {
            Anuncio anuncioo = new Anuncio();
            if(anuncio != null)
                anuncioo = await anuncioo.GetByID(anuncio);
            if (anuncio == null ||anuncioo.Foto == null)
            {
                string fileName = HttpContext.Server.MapPath(@"~/Imagens/admin.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");
            }
            return new FileContentResult(anuncioo.Foto, "image/png");
        }

        public async Task<ActionResult> Categoria(int? page, int cat)
        {
            int pagina = page ?? 1;
            var anuncios = await anuncio.GetAnuncios();
            ViewBag.Categoria = cat;
            return View(anuncio.GetAnunciosCategoria(pagina, cat, anuncios));
        }
    }
}

OrganWeb/OrganWeb/Areas/Ecommerce/Views/Loja/Categoria.cshtml
@using PagedList;
@model IPagedList<OrganWeb.Areas.Ecommerce.Models.Vendas.Anuncio>
@using PagedList.Mvc;
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Categoria";
    Layout = null;
}

@foreach (var item in Model)
{
    <div class="col-md-6 col-lg-3">
        <div class="product">
            <div class="product-img">
                <img src="@Url.Action("FotoDoAnuncio", "Loja", new { Area = "Ecommerce", anuncio = item.Id })" alt="">
                <div class="product-label">
                    @if (item.Desconto > 0)
                    {
                        <span class="sale">-@Html.DisplayFor(modelItem => item.Desconto)%</span>
                    }
                </div>
            </div>
            <div class="product-body">
                <p class="product-category">@Html.DisplayFor(model => item.Produto.Categorias.Where(x => x.Value == item.Produto.Categoria.ToString()).First().Text)</p>
                <h3 class="product-name"><a href="#">@Html.DisplayFor(modelItem => item.Nome)<br /><i class="icon-room"></i>@Html.DisplayFor(modelItem => item.Anunciante.Endereco.Logradouro.Bairro.Cidade.Nome) - @Html.DisplayFor(modelItem => item.Anunciante.Endereco.Logradouro.Bairro.Cidade.Estado.UF)</a></h3>
                @if (item.Desconto > 0)
                {
                    double valornovo = Math.Round(item.Produto.ValorUnit - ((item.Produto.ValorUnit * item.Desconto??0) / 100), 2, MidpointRounding.ToEven);
                    <h4 class="product-price">
                        R$ @valornovo
                        <del class="product-old-price">R$ @Html.DisplayFor(modelItem => item.Produto.ValorUnit)</del>
                    </h4>
                }
                else
                {
                    <h4 class="product-price">
                        R$ @Html.DisplayFor(modelItem => item.Produto.ValorUnit)
                    </h4>
                }
                <div class="product-rating">
                    @for (var i = 1; i <= item.Estrelas; i++)
                    {
                        <i class="mdi mdi-star"></i>
                    }
                    @if (item.Estrelas < 5)
                    {
                        for (var i = 1; i <= (5 - item.Estrelas); i++)
                        {
                            <i class="mdi mdi-star-outline"></i>
                        }
                    }
                </div>
                <div class="product-btns">
                    @if (Request.IsAuthenticated && item.Anunciante.IdUsuario == User.Identity.GetUserId())
                    {
                        <a class="quick-view" href="@Url.Action("Detalhes", "Anuncio", new { id = item.Id })"><i class="mdi mdi-information-outline"></i><span class="tooltipp" value="Detalhes"></span></a>
                    }
                    else
                    {
                        using (Html.BeginForm("AddWishlist", "Wishlist", new { idAnuncio = item.Id }, FormMethod.Post))
                        {
                            @Html.AntiForgeryToken();
                            <button class="add-to-wishlist" type="submit" value="@item.Id"><i class="mdi mdi-cards-heart"></i><span class="tooltipp" value="Adicionar na lista de desejos"></span></button>
                        }
                        using (Html.BeginForm("AddAoCarrinho", "Carrinho", new { idAnuncio = item.Id }, FormMethod.Post))
                        {
                            @Html.AntiForgeryToken();
                            <button class="add-to-compare" type="submit" value="@item.Id"><i class="mdi mdi-cart-plus"></i><span class="tooltipp" value="Adicionar no carrinho"></span></button>
                        }
                        <a class="quick-view" href="@Url.Action("Detalhes", "Anuncio", new { id = item.Id })"><i class="mdi mdi-information-outline"></i><span class="tooltipp" value="Detalhes"></span></a>
                    }
                </div>
            </div>
        </div>
    </div>
    <!-- /product -->
}
<br />
        Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Index",
            new { page, cat = ViewBag.Categoria }), new PagedListRenderOptions
            {
                LiElementClasses = new string[] { "pagination page-item p1" }
            })

OrganWeb/OrganWeb/Areas/Ecommerce/Views/Loja/Pesquisa.cshtml
@using PagedList;
@model IPagedList<OrganWeb.Areas.Ecommerce.Models.Vendas.Anuncio>
@using PagedList.Mvc;
@{
    Layout = "~/Views/Shared/_LayoutEcommerce.cshtml";
}

<div class="hero-wrap hero-bread">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2">Início /</span><span class="mr-2">Pesquisa</span></p>
                <h1 class="mb-0 bread">Pesquisa</h1>
            </div>
        </div>
    </div>
</div>
<div class="site-section">
    <div class="container md-margin-top-50px">
        <div class="row mb-5">
            <div class="col-md-9 order-2">
                <div class="row">
                    <div class="col-md-12 mb-5">
                        <div class="float-md-left mb-4"><h2 class="text-black h5">Produtos</h2></div>
                    </div>
                </div>

                <div class="row mb-5">

                    @foreach (var item in Model)
                    {
                        <div class="col-md-6 col-lg-3 ftco-animate">
                            <div class="product">
                                <a href="@Url.Action("Detalhes", "Anuncio", new { id = item.Id })" class="img-prod">
                                    <img src="@Url.Action("FotoDoAnuncio", "Loja", new { Area = "Ecommerce", anuncio = item.Id })" alt="">
                                    @if (item.Desconto > 0)
                                    {
                                        <span class="status">-@Html.DisplayFor(modelItem => item.Desconto)%</span>
                                    }
                                    <div class="overlay"></div>
                                </a>
                                <div class="text py-3 pb-4 px-3 text-center">
                                    <p class="product-category">@Html.DisplayFor(model => item.Produto.Categorias.Where(x => x.Value == item.Produto.Categoria.ToString()).First().Text)</p>
                                    <h3 class="product-name"><a href="#">@Html.DisplayFor(modelItem => item.Nome)<br /><i class="icon-room"></i>@Html.DisplayFor(modelItem => item.Anunciante.Endereco.Logradouro.Bairro.Cidade.Nome) - @Html.DisplayFor(modelItem => item.Anunciante.Endereco.Logradouro.Bairro.Cidade.Estado.UF)</a></h3>
                                    <div class="product-rating">
                                        @for (var i = 1; i <= item.Estrelas; i++)
                                        {
                                            <i class="mdi mdi-star"></i>
                                        }
                                        @if (item.Estrelas < 5)
                                        {
                                            for (var i = 1; i <= (5 - item.Estrelas); i++)
                                            {
                                                <i class="mdi mdi-star-outline"></i>
                                            }
                                        }
                                    </div>
                                    <div class="d-flex">
                                        <div class="pricing">
                                            @if (item.Desconto > 0)
                                            {
                                                double valornovo = Math.Round(item.Produto.ValorUnit - ((item.Produto.ValorUnit * item.Desconto ?? 0) / 100), 2, MidpointRounding.ToEven);

                                                <p class="price"><span class="mr-2 price-dc">R$ @Html.DisplayFor(modelItem => item.Produto.ValorUnit)</span><span class="price-sale">R$ @valornovo</span></p>

                                            }
                                            else
                                            {
                                                <p class="price">
                                                    <span class="price-sale">
                                                        R$ @Html.DisplayFor(modelItem => item.Produto.ValorUnit)
                                                    </span>
                                                </p>
                                            }
                                        </div>
                                    </div>
                                    <div class="bottom-area d-flex px-3">
                                        <div class="m-auto d-flex">
                                            @using (Html.BeginForm("AddWishlist", "Wishlist", new { idAnuncio = item.Id }, FormMethod.Post))
                                            {
                                                @Html.AntiForgeryToken();
                                                <button type="submit" value="@item.Id" class="buy-now d-flex justify-content-center align-items-center mx-1">
                                                    <span><i class="mdi mdi-cards-heart"></i></span>
                                                </button>
                                            }
                                            @using (Html.BeginForm("AddAoCarrinho", "Carrinho", new { idAnuncio = item.Id }, FormMethod.Post))
                                            {
                                                @Html.AntiForgeryToken();
                                                <button type="submit" value="@item.Id" class="buy-now d-flex justify-content-center align-items-center mx-1">
                                                    <span><i class="mdi mdi-cart-plus"></i></span>
                                                </button>
                                            }
                                            <a href="@Url.Action("Detalhes", "Anuncio", new { id = item.Id })" class="heart d-flex justify-content-center align-items-center ">
                                                <span><i class="mdi mdi-information-outline"></i></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </div>

                    <div class="row">
                        <div class="col-md-12 text-center">
                            <div class="site-block-27">
                                <ul>
                                    Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

                                    @Html.PagedListPager(Model, page => Url.Action("Index",
                                        new { page, cat = ViewBag.Categoria }), new PagedListRenderOptions
                                        {
                                            LiElementClasses = new string[] { "pagination page-item p1" }
                                        })
                                </ul>
                            </div>
                        </div>
                    </div>
                
            </div>
                        <div class="col-md-3 order-1 mb-5 mb-md-0">
                            <div class="border p-4 rounded mb-4">
                                <h3 class="mb-3 h6 text-uppercase text-black d-block">Categorias</h3>
                                <div class="input-checkbox">
                                    <input type="checkbox" id="category-4">
                                    <label for="category-4">
                                        <span></span>
                                        Sementes
                                        <small>(1478)</small>
                                    </label>
                                </div>
                                <div class="input-checkbox">
                                    <input type="checkbox" id="category-4">
                                    <label for="category-4">
                                        <span></span>
                                        Máquinas
                                        <small>(268)</small>
                                    </label>
                                </div>
                                <div class="input-checkbox">
                                    <input type="checkbox" id="category-4">
                                    <label for="category-4">
                                        <span></span>
                                        Vegetais
                                        <small>(2654)</small>
                                    </label>
                                </div>
                                <div class="input-checkbox">
                                    <input type="checkbox" id="category-4">
                                    <label for="category-4">
                                        <span></span>
                                        Frutas
                                        <small>(3478)</small>
                                    </label>
                                </div>
                            </div>
                            <div class="border p-4 rounded mb-4">
                                <div class="mb-4">
                                    <h3 class="mb-3 h6 text-uppercase text-black d-block">Filtrar por preço</h3>
                                    <div id="slider-range" class="border-primary"></div>
                                    <input type="text" name="text" id="amount" class="form-control border-0 pl-0 bg-white" disabled="" />
                                </div>
                                <div class="mb-4">
                                    <h3 class="mb-3 h6 text-uppercase text-black d-block">Localização</h3>
                                    <label for="s_sm" class="d-flex">
                                        <input type="checkbox" id="s_sm" class="mr-2 mt-1"> <span class="text-black">Norte (2,319)</span>
                                    </label>
                                    <label for="s_md" class="d-flex">
                                        <input type="checkbox" id="s_md" class="mr-2 mt-1"> <span class="text-black">Nordeste (1,882)</span>
                                    </label>
                                    <label for="s_lg" class="d-flex">
                                        <input type="checkbox" id="s_lg" class="mr-2 mt-1"> <span class="text-black">Centro-oeste (3,392)</span>
                                    </label>
                                    <label for="s_lg" class="d-flex">
                                        <input type="checkbox" id="s_lg" class="mr-2 mt-1"> <span class="text-black">Sudeste (1,094)</span>
                                    </label>
                                    <label for="s_lg" class="d-flex">
                                        <input type="checkbox" id="s_lg" class="mr-2 mt-1"> <span class="text-black">Sul (2,334)</span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
</div>
          